FLAGS = -g -Wall -lcrypto

CXX = gcc

Rm = rm -f

all:
	$(CXX) -o criptografia.exe criptoRSA.c $(FLAGS)
	# $(CXX) -o sequencial.exe src/sequencial_paralelo_smith_waterman.c $(FLAGS)

clean:
	$(RM) -f *.exe
